version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: mock-node-db
    restart: always
    environment:
      POSTGRES_USER: user        
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: mock_node_db  
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: